apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2022-08-04T09:01:11Z"
  generateName: metrics-server-668d979685-asdasd
  labels:
    k8s-app: metrics-server
    pod-template-hash: 668d979685
  name: metrics-server-668d979685-bbpv7
  namespace: kube-system
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: metrics-server-668d979685
    uid: 89dcc495-750c-4c36-b1fd-ecfdada62657
  resourceVersion: "858945"
  uid: 1d35ef25-b187-4986-950b-197cfd64dc9e
spec:
  containers:
  - args:
    - --cert-dir=/tmp
    - --secure-port=4443
    - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
    - --kubelet-use-node-status-port
    - --metric-resolution=15s
    image: rancher/mirrored-metrics-server:v0.5.2
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /livez
        port: https
        scheme: HTTPS
      initialDelaySeconds: 60
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    name: metrics-server
    ports:
    - containerPort: 4443
      name: https
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /readyz
        port: https
        scheme: HTTPS
      periodSeconds: 2
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      requests:
        cpu: 100m
        memory: 70Mi
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /tmp
      name: tmp-dir
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-qvnm5
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: k3s
  preemptionPolicy: PreemptLowerPriority
  priority: 2000001000
  priorityClassName: system-node-critical
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: metrics-server
  serviceAccountName: metrics-server
  terminationGracePeriodSeconds: 30
  tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
    operator: Exists
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - emptyDir: {}
    name: tmp-dir
  - name: kube-api-access-qvnm5
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-08-04T09:01:13Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-04-24T15:24:15Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-04-24T15:24:15Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2022-08-04T09:01:13Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://444775a3fb8b6a1face92163deca03725b14e793837227cc0d9b55dc93ae63f1
    image: docker.io/rancher/mirrored-metrics-server:v0.5.2
    imageID: docker.io/rancher/mirrored-metrics-server@sha256:48ecad4fe641a09fa4459f93c7ad29d4916f6b9cf7e934d548f1d8eff96e2f35
    lastState:
      terminated:
        containerID: containerd://3d740c7f7f1f9f32cfceee4aa1a07aeed7e4bb5a62419a77c1b4502709493e73
        exitCode: 2
        finishedAt: "2023-04-24T15:23:39Z"
        reason: Error
        startedAt: "2023-04-24T15:23:08Z"
    name: metrics-server
    ready: true
    restartCount: 41
    started: true
    state:
      running:
        startedAt: "2023-04-24T15:24:00Z"
  hostIP: 192.168.64.2
  phase: Running
  podIP: 10.42.0.156
  podIPs:
  - ip: 10.42.0.156
  qosClass: Burstable
  startTime: "2022-08-04T09:01:13Z"
